services:
  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${USER_DATABASE}
      POSTGRES_PASSWORD: ${PASSWORD_DATABASE}
      POSTGRES_DB: ${NAME_DATABASE}
      PGDATA: /var/lib/postgresql/data/
    volumes:
       - ./database/postgres/:/var/lib/postgresql/data
    ports:
      - "${PORT_DATABASE}:${PORT_DATABASE}"
    restart: always